package mikeshafter.iciwi.faregate;

import org.junit.Test;
import org.bukkit.block.BlockFace;
import org.bukkit.util.Vector;

import static org.junit.jupiter.api.Assertions.*;

public class CardUtilTest {

// TEST METHOD BEGIN

  /**
   * Changes arbitrary sign directions into cartesian (one cardinal direction only) directions.
   * This method has a clockwise bias.
   * @param face the original direction
   * @return the altered direction
   */
  public static BlockFace toCartesian (BlockFace face) {
    if (!face.isCartesian()) {
      return switch (face) {
        case NORTH_WEST, NORTH_NORTH_WEST, NORTH_NORTH_EAST -> BlockFace.NORTH;
        case NORTH_EAST, EAST_NORTH_EAST, EAST_SOUTH_EAST -> BlockFace.EAST;
        case SOUTH_EAST, SOUTH_SOUTH_EAST, SOUTH_SOUTH_WEST -> BlockFace.SOUTH;
        case SOUTH_WEST, WEST_SOUTH_WEST, WEST_NORTH_WEST -> BlockFace.WEST;
        default -> face;
      };
    } else return face;
  }

  /**
   * Gets the direction to build and animate fare gates in.
   * The animation direction should be the opposite direction to the build direction.
   * @param signDirection the direction of the sign
   * @param flags the flags to be applied
   * @return the direction to build fare gates in.
   */
  public static Vector toBuildDirection (BlockFace signDirection, int flags) {
    if ((flags & 1 | flags & 16) != 0) return new Vector();	// Validator and Redstone: no animation/double gate allowed
    else if ((flags & 2) != 0) return signDirection.getDirection().getCrossProduct(new Vector(0, 1, 0));	// Lefty
    else if ((flags & 4) != 0) return signDirection.getDirection();	// Sideways
    else return signDirection.getDirection().getCrossProduct(new Vector(0, -1, 0));	// Normal
  }

  /**
   * Gets the relative positions of the fare gate blocks, with direction accounted for
   * The length of the returned Vector[] can be of length 0, 1, or 2.
   * @param signDirection the sign's facing direction
   * @param flags the flags to be applied
   * @param buildDirection the direction to build fare gates in
   * @return The positions of the fare gate blocks.
   */
  public static Vector[] toPos (BlockFace signDirection, int flags) {
    // length 0 if validator
    if ((flags & 1) != 0) return new Vector[0];

    // initialise vector array and default position vector
    Vector[] v = (flags & 8) == 0 ? new Vector[1] : new Vector[2];
    v[0] = signDirection.getDirection().getCrossProduct(new Vector(0, -1, 0));

    // parse default, S, E, R, F flags
    if ((flags &  4) != 0) v[0].add(signDirection.getDirection());
    if ((flags & 32) != 0) v[0].subtract(new Vector(0, 1, 0));
    if ((flags & 16) != 0) v[0] = new Vector(0, -2, 0);
    if ((flags & 64) != 0) v[0] = new Vector(0, 2, 0);
    // parse L flag
    if ((flags & 2) != 0 && (signDirection == BlockFace.SOUTH || signDirection == BlockFace.NORTH)) v[0].multiply(new Vector(-1, 1, 1));
    if ((flags & 2) != 0 && (signDirection == BlockFace.EAST  || signDirection == BlockFace.WEST )) v[0].multiply(new Vector(1, 1, -1));

    // parse D flag
    if ((flags & 8) != 0) v[1] = v[0].add(toBuildDirection(signDirection, flags));

    // return
    return v;
  }

// TEST METHOD END


  @Test
  public void toCartesianTest () {

    // Test values
    var testValues = new BlockFace[][] {
      new BlockFace[] {BlockFace.EAST, BlockFace.EAST},
      new BlockFace[] {BlockFace.SOUTH, BlockFace.SOUTH},
      new BlockFace[] {BlockFace.WEST, BlockFace.WEST},
      new BlockFace[] {BlockFace.NORTH, BlockFace.NORTH},

      new BlockFace[] {BlockFace.EAST, BlockFace.NORTH_EAST},
      new BlockFace[] {BlockFace.SOUTH, BlockFace.SOUTH_EAST},
      new BlockFace[] {BlockFace.WEST, BlockFace.SOUTH_WEST},
      new BlockFace[] {BlockFace.NORTH, BlockFace.NORTH_WEST},

      new BlockFace[] {BlockFace.EAST, BlockFace.EAST_NORTH_EAST},
      new BlockFace[] {BlockFace.EAST, BlockFace.EAST_SOUTH_EAST},
      new BlockFace[] {BlockFace.SOUTH, BlockFace.SOUTH_SOUTH_WEST},
      new BlockFace[] {BlockFace.SOUTH, BlockFace.SOUTH_SOUTH_EAST},
      new BlockFace[] {BlockFace.WEST, BlockFace.WEST_NORTH_WEST},
      new BlockFace[] {BlockFace.WEST, BlockFace.WEST_SOUTH_WEST},
      new BlockFace[] {BlockFace.NORTH, BlockFace.NORTH_NORTH_EAST},
      new BlockFace[] {BlockFace.NORTH, BlockFace.NORTH_NORTH_WEST},
    };

    // Assert every value
    for (var value : testValues) {
      var expected = value[0];
      var face = value[1];
      assertEquals(expected, toCartesian(face));
    }
  }


  @Test
  public void toBuildDirectionTest () {

    // Test values
    var testValues = new Object[][] {   
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 0},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 1},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 2},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 3},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 4},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 5},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 6},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 7},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 8},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 9},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 10},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 11},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 12},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 13},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 14},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 15},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 16},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 17},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 18},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 19},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 20},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 21},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 22},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 23},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 24},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 25},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 26},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 27},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 28},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 29},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 30},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 31},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 32},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 33},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 34},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 35},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 36},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 37},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 38},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 39},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 40},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 41},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 42},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 43},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 44},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 45},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 46},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 47},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 48},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 49},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 50},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 51},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 52},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 53},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 54},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 55},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 56},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 57},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 58},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 59},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 60},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 61},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 62},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 63},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 64},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 65},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 66},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 67},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 68},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 69},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 70},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 71},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 72},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 73},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 74},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 75},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 76},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 77},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 78},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 79},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 80},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 81},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 82},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 83},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 84},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 85},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 86},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 87},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 88},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 89},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 90},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 91},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 92},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 93},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 94},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 95},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 96},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 97},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 98},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 99},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 100},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 101},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 102},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 103},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 104},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 105},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 106},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 107},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 108},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 109},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 110},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 111},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 112},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 113},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 114},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 115},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 116},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 117},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 118},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 119},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 120},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 121},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 122},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 123},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 124},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 125},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 126},
      new Object[] {new Vector(1,1,1), BlockFace.EAST, 127},
            
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 0},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 1},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 2},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 3},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 4},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 5},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 6},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 7},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 8},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 9},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 10},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 11},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 12},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 13},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 14},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 15},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 16},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 17},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 18},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 19},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 20},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 21},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 22},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 23},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 24},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 25},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 26},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 27},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 28},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 29},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 30},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 31},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 32},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 33},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 34},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 35},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 36},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 37},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 38},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 39},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 40},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 41},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 42},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 43},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 44},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 45},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 46},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 47},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 48},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 49},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 50},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 51},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 52},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 53},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 54},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 55},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 56},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 57},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 58},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 59},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 60},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 61},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 62},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 63},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 64},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 65},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 66},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 67},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 68},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 69},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 70},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 71},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 72},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 73},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 74},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 75},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 76},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 77},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 78},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 79},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 80},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 81},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 82},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 83},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 84},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 85},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 86},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 87},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 88},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 89},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 90},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 91},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 92},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 93},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 94},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 95},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 96},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 97},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 98},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 99},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 100},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 101},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 102},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 103},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 104},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 105},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 106},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 107},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 108},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 109},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 110},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 111},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 112},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 113},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 114},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 115},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 116},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 117},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 118},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 119},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 120},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 121},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 122},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 123},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 124},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 125},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 126},
      new Object[] {new Vector(1,1,1), BlockFace.SOUTH, 127},
      
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 0},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 1},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 2},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 3},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 4},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 5},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 6},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 7},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 8},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 9},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 10},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 11},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 12},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 13},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 14},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 15},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 16},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 17},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 18},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 19},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 20},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 21},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 22},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 23},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 24},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 25},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 26},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 27},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 28},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 29},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 30},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 31},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 32},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 33},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 34},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 35},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 36},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 37},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 38},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 39},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 40},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 41},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 42},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 43},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 44},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 45},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 46},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 47},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 48},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 49},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 50},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 51},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 52},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 53},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 54},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 55},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 56},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 57},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 58},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 59},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 60},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 61},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 62},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 63},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 64},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 65},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 66},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 67},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 68},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 69},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 70},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 71},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 72},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 73},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 74},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 75},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 76},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 77},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 78},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 79},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 80},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 81},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 82},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 83},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 84},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 85},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 86},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 87},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 88},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 89},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 90},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 91},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 92},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 93},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 94},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 95},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 96},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 97},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 98},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 99},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 100},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 101},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 102},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 103},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 104},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 105},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 106},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 107},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 108},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 109},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 110},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 111},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 112},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 113},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 114},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 115},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 116},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 117},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 118},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 119},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 120},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 121},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 122},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 123},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 124},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 125},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 126},
      new Object[] {new Vector(1,1,1), BlockFace.WEST, 127},
      
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 0},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 1},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 2},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 3},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 4},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 5},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 6},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 7},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 8},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 9},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 10},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 11},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 12},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 13},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 14},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 15},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 16},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 17},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 18},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 19},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 20},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 21},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 22},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 23},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 24},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 25},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 26},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 27},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 28},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 29},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 30},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 31},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 32},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 33},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 34},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 35},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 36},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 37},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 38},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 39},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 40},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 41},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 42},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 43},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 44},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 45},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 46},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 47},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 48},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 49},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 50},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 51},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 52},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 53},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 54},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 55},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 56},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 57},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 58},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 59},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 60},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 61},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 62},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 63},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 64},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 65},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 66},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 67},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 68},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 69},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 70},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 71},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 72},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 73},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 74},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 75},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 76},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 77},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 78},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 79},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 80},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 81},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 82},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 83},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 84},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 85},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 86},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 87},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 88},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 89},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 90},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 91},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 92},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 93},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 94},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 95},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 96},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 97},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 98},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 99},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 100},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 101},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 102},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 103},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 104},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 105},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 106},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 107},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 108},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 109},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 110},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 111},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 112},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 113},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 114},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 115},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 116},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 117},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 118},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 119},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 120},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 121},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 122},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 123},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 124},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 125},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 126},
      new Object[] {new Vector(1,1,1), BlockFace.NORTH, 127},
    };

    // Assert every value
    for (var value : testValues) {
      var expected = value[0];
      var signDirection = (BlockFace) value[1];
      var flags = (Integer) value[2];
      assertEquals(expected, toBuildDirection(signDirection, flags));
    }
  }

  
  @Test
  public void toPosTest () {

    // Test values
    var testValues = new Object[][] {
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 0},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 1},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 2},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 3},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 4},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 5},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 6},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 7},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 8},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 9},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 10},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 11},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 12},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 13},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 14},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 15},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 16},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 17},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 18},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 19},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 20},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 21},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 22},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 23},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 24},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 25},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 26},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 27},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 28},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 29},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 30},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 31},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 32},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 33},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 34},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 35},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 36},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 37},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 38},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 39},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 40},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 41},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 42},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 43},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 44},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 45},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 46},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 47},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 48},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 49},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 50},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 51},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 52},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 53},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 54},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 55},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 56},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 57},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 58},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 59},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 60},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 61},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 62},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 63},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 64},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 65},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 66},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 67},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 68},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 69},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 70},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 71},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 72},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 73},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 74},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 75},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 76},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 77},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 78},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 79},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 80},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 81},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 82},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 83},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 84},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 85},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 86},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 87},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 88},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 89},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 90},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 91},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 92},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 93},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 94},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 95},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 96},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 97},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 98},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 99},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 100},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 101},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 102},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 103},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 104},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 105},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 106},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 107},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 108},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 109},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 110},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 111},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 112},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 113},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 114},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 115},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 116},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 117},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 118},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 119},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 120},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 121},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 122},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 123},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 124},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 125},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 126},
      new Object[] {asVectorArray(1,1,1), BlockFace.EAST, 127},
      
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 0},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 1},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 2},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 3},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 4},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 5},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 6},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 7},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 8},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 9},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 10},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 11},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 12},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 13},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 14},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 15},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 16},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 17},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 18},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 19},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 20},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 21},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 22},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 23},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 24},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 25},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 26},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 27},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 28},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 29},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 30},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 31},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 32},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 33},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 34},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 35},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 36},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 37},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 38},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 39},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 40},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 41},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 42},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 43},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 44},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 45},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 46},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 47},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 48},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 49},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 50},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 51},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 52},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 53},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 54},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 55},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 56},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 57},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 58},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 59},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 60},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 61},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 62},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 63},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 64},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 65},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 66},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 67},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 68},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 69},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 70},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 71},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 72},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 73},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 74},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 75},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 76},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 77},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 78},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 79},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 80},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 81},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 82},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 83},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 84},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 85},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 86},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 87},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 88},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 89},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 90},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 91},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 92},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 93},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 94},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 95},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 96},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 97},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 98},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 99},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 100},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 101},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 102},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 103},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 104},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 105},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 106},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 107},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 108},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 109},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 110},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 111},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 112},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 113},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 114},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 115},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 116},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 117},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 118},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 119},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 120},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 121},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 122},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 123},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 124},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 125},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 126},
      new Object[] {asVectorArray(1,1,1), BlockFace.SOUTH, 127},
      
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 0},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 1},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 2},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 3},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 4},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 5},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 6},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 7},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 8},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 9},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 10},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 11},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 12},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 13},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 14},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 15},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 16},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 17},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 18},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 19},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 20},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 21},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 22},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 23},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 24},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 25},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 26},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 27},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 28},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 29},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 30},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 31},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 32},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 33},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 34},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 35},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 36},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 37},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 38},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 39},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 40},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 41},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 42},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 43},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 44},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 45},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 46},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 47},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 48},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 49},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 50},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 51},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 52},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 53},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 54},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 55},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 56},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 57},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 58},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 59},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 60},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 61},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 62},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 63},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 64},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 65},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 66},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 67},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 68},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 69},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 70},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 71},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 72},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 73},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 74},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 75},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 76},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 77},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 78},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 79},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 80},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 81},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 82},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 83},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 84},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 85},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 86},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 87},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 88},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 89},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 90},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 91},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 92},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 93},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 94},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 95},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 96},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 97},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 98},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 99},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 100},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 101},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 102},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 103},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 104},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 105},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 106},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 107},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 108},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 109},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 110},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 111},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 112},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 113},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 114},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 115},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 116},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 117},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 118},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 119},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 120},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 121},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 122},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 123},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 124},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 125},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 126},
      new Object[] {asVectorArray(1,1,1), BlockFace.WEST, 127},
            
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 0},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 1},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 2},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 3},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 4},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 5},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 6},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 7},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 8},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 9},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 10},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 11},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 12},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 13},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 14},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 15},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 16},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 17},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 18},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 19},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 20},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 21},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 22},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 23},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 24},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 25},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 26},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 27},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 28},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 29},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 30},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 31},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 32},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 33},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 34},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 35},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 36},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 37},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 38},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 39},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 40},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 41},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 42},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 43},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 44},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 45},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 46},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 47},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 48},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 49},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 50},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 51},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 52},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 53},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 54},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 55},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 56},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 57},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 58},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 59},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 60},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 61},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 62},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 63},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 64},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 65},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 66},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 67},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 68},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 69},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 70},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 71},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 72},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 73},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 74},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 75},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 76},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 77},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 78},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 79},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 80},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 81},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 82},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 83},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 84},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 85},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 86},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 87},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 88},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 89},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 90},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 91},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 92},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 93},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 94},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 95},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 96},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 97},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 98},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 99},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 100},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 101},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 102},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 103},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 104},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 105},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 106},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 107},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 108},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 109},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 110},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 111},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 112},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 113},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 114},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 115},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 116},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 117},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 118},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 119},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 120},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 121},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 122},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 123},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 124},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 125},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 126},
      new Object[] {asVectorArray(1,1,1), BlockFace.NORTH, 127},
    };

    // Assert every value
    for (var value : testValues) {
      var expected = value[0];
      var signDirection = (BlockFace) value[1];
      var flags = (Integer) value[2];
      var buildDirection = (Vector) value[3];
      assertEquals(expected, toPos(signDirection, flags));
    }

  }

  // Helper method
  private Vector[] asVectorArray(int... coordinates) {
    if (coordinates.length % 3 != 0) {
      return null;
    }
    Vector[] returnArray = new Vector[coordinates.length/3];
    for (int i = 0; i < coordinates.length; i += 3) {
      returnArray[i/3] = new Vector(coordinates[i], coordinates[i+1], coordinates[i+2]);
    }
    return returnArray;
  }

}

